### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rigler86** [Opzet/SoftwareLicenseManager#1]
so from my understanding i can use https://www.10quality.com/product/woocommerce-license-keys/ to issue license and manage them for a c# app I have? is this the best one for simplicity?

I'm new to all this. i have a program I had made by someone and need a way to lock it down using wordpress.

**Comment by Opzet** [comment]
This is the best for the price (free) but is not the best one for simplicity as it requires your, app developer ( @i have a program I had made by someone) to implement the code.  :)

**Comment by rigler86** [comment]
I have some programming knowledge. Im just a bit confused with the write
up.
